web/router.ex
defmodule Jumper.Router do
  use Jumper.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Jumper.AssignUser
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Jumper.Authenticate
  end

  scope "/", Jumper do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/registraions", RegistrationController, only: [:new, :create]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/rooms", Jumper do
    pipe_through [:browser, :auth]

    resources "/", RoomController, only: [:index, :show, :new, :create]
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Jumper do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Jumper.LayoutView do
  use Jumper.Web, :view
end

web/templates/layout/_header.html.eex
<header class="header">
  <nav role="navigation">
    <ul class="nav nav-pills pull-right">
    <%= if logged_in?(@conn) do %>
      <li><%= current_user(@conn).email %></li>
      <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
    <% else %>
      <li><%= link "Login", to: session_path(@conn, :new) %></li>
      <li><%= link "Register", to: registration_path(@conn, :new) %></li>
    <% end %>
    </ul>
  </nav>
</header>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jumper</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  </head>

  <body>
    <div class="fluid-container">
      <%= render "_header.html", conn: @conn %>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/chat.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Jumper</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
</head>

<body>
<div class="fluid-container">
  <main role="main">
    <%= render @view_module, @view_template, assigns %>
  </main>

</div> <!-- /container -->

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>